pip install numpy first

In [5]:
import numpy as np

In [6]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [7]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0,]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
#Get Dimension
a.ndim

1

In [9]:
#Get Shape
a.shape

(3,)

In [10]:
#Get Type
a.dtype

dtype('int32')

In [11]:
#Get total size
a.size

3

In [12]:
a.size*a.itemsize

12

In [13]:
a.nbytes

12

# Accessing/changing specific elements,rows,columns,etc

In [14]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
#Get a specific element [r , c]
a[1,5]

13

In [16]:
a[1,-2]

13

In [17]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [19]:
#Getting a element [startindex:endindex:stepsize]
a[0,1:-2:2]

array([2, 4])

In [20]:
a[1,5]=20
print(a)

a[:,2]=[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [21]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
#Get a specific element (work outside in)
b[0,1,1]

4

In [23]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [24]:
#replace 
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [25]:
#All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.zeros((2,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [29]:
#All 1s matrix 
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [30]:
#Any other number 
np.full((2,2),99,dtype='float')

array([[99., 99.],
       [99., 99.]])

In [31]:
#Any other number (full_like)
np.full_like(a,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
#random decimal numbers 
np.random.rand(4,2)

array([[0.1763171 , 0.65836799],
       [0.48556137, 0.50544076],
       [0.56418902, 0.77428043],
       [0.71854018, 0.59934059]])

In [35]:
#random integer values
np.random.randint(4,8, size=(3,3))

array([[7, 6, 4],
       [4, 5, 5],
       [7, 7, 7]])

In [36]:
np.random.randint(-4,8,size=(3,3))

array([[ 4,  7,  5],
       [ 3,  0, -3],
       [-3,  5,  6]])

In [37]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [39]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]+z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# coping arrays

In [40]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

[100   2   3]


In [41]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


In [42]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)

[100   2   3]


# Mathematics

In [49]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [50]:
a+=2
print(a)

[3 4 5 6]


In [52]:
a-=2
print(a)

[-1  0  1  2]


In [53]:
a*2
a

array([-1,  0,  1,  2])

In [54]:
a/2

array([-0.5,  0. ,  0.5,  1. ])

In [56]:
b=np.array([1,0,1,0])
a+b

array([0, 0, 2, 2])

In [57]:
a**2

array([1, 0, 1, 4], dtype=int32)

In [58]:
#take the sin
np.cos(a)

array([ 0.54030231,  1.        ,  0.54030231, -0.41614684])

# Linear Algebra

In [61]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [62]:
#Find the determinent
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [63]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.min(stats,axis=0)

array([1, 2, 3])

In [65]:
np.min(stats,axis=1)

array([1, 4])

In [66]:
np.max(stats,axis=0)

array([4, 5, 6])

In [67]:
np.max(stats,axis=1)

array([3, 6])

In [68]:
np.max(stats)

6

# Reorganizing Arrays

In [70]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [75]:
#vertically stacking vectors
v1 =np.array([1,2,3,4])
v2 =np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
#Horizontal stack
h1 =np.ones((2,4))
h2=np.zeros((2,2,))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [79]:
a=np.arange(12).reshape(4,3)**2
print("Let's consider an array\n",a)
print("\n")
for i in a:
 print(i*2)

Let's consider an array
 [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


[0 2 8]
[18 32 50]
[ 72  98 128]
[162 200 242]


# Matrix operations

In [80]:
a=np.floor(10*np.random.random((3,4)))
print("Let's consider a 1-D array\n",a)
print("After reshaping to 2 by 6 matrix\n",a.reshape(2,6))
print("To Flatten the array\n",a.ravel())
print("To transpose the array\n",a.T)

Let's consider a 1-D array
 [[5. 3. 6. 3.]
 [1. 5. 1. 8.]
 [7. 7. 8. 0.]]
After reshaping to 2 by 6 matrix
 [[5. 3. 6. 3. 1. 5.]
 [1. 8. 7. 7. 8. 0.]]
To Flatten the array
 [5. 3. 6. 3. 1. 5. 1. 8. 7. 7. 8. 0.]
To transpose the array
 [[5. 1. 7.]
 [3. 5. 7.]
 [6. 1. 8.]
 [3. 8. 0.]]
